name: News Digest

on:

  schedule:
    - cron: "30 1 * * *"

  workflow_dispatch:

jobs:

  news:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:
          python-version: "3.12"

      - run: |
          pip install requests
          pip install beautifulsoup4

      - run: python news_fetch.py

      - run: python email_sender.py